version: "3.8"

services:

  db:
    image: postgres
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: hippy
      POSTGRES_PASSWORD: pippy
      POSTGRES_DB: yippy
    networks:
      default:
    volumes:
      - db_vol:/var/lib/postgresql/data

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    # network_mode: bridge
    # image: localstack/localstack:2.0.2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "127.0.0.1:4572:4572" #S3
      # - "53:53"
      # - "53:53/udp"
      # - "443:443"
    environment:
      DEBUG: 1
      DOCKER_HOST: unix:///var/run/docker.sock
      EAGER_SERVICE_LOADING: 1
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      # AWS_DEFAULT_PROFILE: localstack
      LAMBDA_EXECUTOR: "${LAMBDA_EXECUTOR-}"
      PERSISTENCE: /tmp/localstack/data
      LOG_LOG: trace
      SERVICES: lambda,apigateway,s3
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      default:


networks:
  default:
    external:
      name: localstack-tutorial

volumes:
  db_vol:
    external:
      name: "postgresLS"
