version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    # network_mode: bridge
    # image: localstack/localstack:2.0.2
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "127.0.0.1:4566:4566" # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559" # external services port range
      - "53:53"
      - "53:53/udp"
      - "443:443"
    environment:
      DEBUG: 0
      DOCKER_HOST: "unix:///var/run/docker.sock"
      EAGER_SERVICE_LOADING: 1
      SERVICES: lambda
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: testUser
      AWS_SECRET_ACCESS_KEY: testAccessKey
      LAMBDA_EXECUTOR: local
      DATA_DIR: /tmp/localstack/data
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:


networks:
  default:
    external:
      name: localstack-tutorial
